import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.shop': 'SHOP',
    'nav.collections': 'SEASONS',
    'nav.ai': 'SCENT AI',
    'nav.story': 'STORY',
    'nav.login': 'LOGIN',
    'nav.shopAll': 'SHOP ALL',
    'hero.tagline': 'MINIMAL TOUCH, NATURAL SCENT',
    'hero.title': 'Elevate your living space with exquisite, original scents.',
    'hero.subtitle': '100% Soy Wax. Natural Wood Wicks. A healing lifestyle.',
    'hero.cta_shop': 'Discover Collection',
    'hero.cta_ai': 'Scent Sommelier',
    'products.title': 'The Quiet Seasons',
    'products.subtitle': 'A collection inspired by the subtle transitions of nature.',
    'products.viewAll': 'View all candles',
    'product.tab.description': 'Mood',
    'product.tab.details': 'Details',
    'product.tab.shipping': 'Shipping',
    'product.burnTime': 'Burn Time',
    'product.burnTimeValue': '50-60 hours',
    'product.weight': 'Weight',
    'product.weightValue': '8.5 oz (240g)',
    'product.ingredients': 'Ingredients',
    'product.ingredientsValue': 'Natural Soy Wax, FSC-Certified Wood Wick, Fine Fragrance Oils',
    'product.shippingValue': 'Free standard shipping on orders over $75. Ships within 2-3 business days.',
    'product.addToCart': 'Add to Bag',
    'product.category.signature': 'The Quiet Seasons',
    'product.category.seasonal': 'Seasonal Collection',
    'product.category.limited': 'Limited Edition',
    'ai.tagline': 'AI Scent Sommelier',
    'ai.title': 'Describe your moment, let us craft the scent.',
    'ai.subtitle': 'Whether it\'s "morning dew on leaves" or "warmth from a kitchen corner," our AI will find your match.',
    'ai.placeholder': 'e.g., Reading a book by the window while it rains...',
    'ai.button.loading': 'Blending...',
    'ai.button.idle': 'Find Match',
    'ai.error': 'Something went wrong. Please try describing your mood differently.',
    'ai.result.concept': 'Your Concept',
    'ai.result.notes': 'Notes',
    'ai.result.why': 'The Match:',
    'ai.result.again': 'Reset',
    'ai.empty.text': 'Your essence awaits...',
    'blog.title': 'Healing Corner',
    'blog.subtitle': 'Stories of slow living and finding peace at home.',
    'blog.p1.title': 'The Balcony Corner',
    'blog.p1.desc': 'Turning a small outdoor space into a sanctuary for morning coffee and reflection.',
    'blog.p2.title': 'Evening Stories',
    'blog.p2.desc': 'Rituals to unwind after a long day: soft light, gentle music, and the perfect scent.',
    'blog.p3.title': 'Neighbors & Home',
    'blog.p3.desc': 'The joy of sharing warmth and community in our daily lives.',
    'director.title': 'From the Director',
    'director.text': 'Narie is not just about candles; it is about the pause between moments. It is the deep breath you take when you walk through the door. We crafted "The Quiet Seasons" to honor the rhythm of nature and the rhythm of your heart.',
    'director.signoff': '- Narie Creative Director',
    'footer.desc': 'Narie Candle - Minimal Touch, Natural Scent.',
    'footer.shop': 'Shop',
    'footer.company': 'Company',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter_desc': 'Receive letters from Narie.',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved.',
    'footer.links.all': 'All Candles',
    'footer.links.sig': 'Signature Series',
    'footer.links.seasonal': 'Seasonal Drops',
    'footer.links.access': 'Accessories',
    'footer.links.story': 'Our Story',
    'footer.links.sus': 'Sustainability',
    'footer.links.stock': 'Stockists',
    'footer.links.contact': 'Contact',
    'footer.links.privacy': 'Privacy Policy',
    'footer.links.terms': 'Terms of Service',
    'app.quote': '"We believe that a scent is more than just fragrance; it is a memory waiting to be lit."',
    'app.about.title': 'About Narie',
    'app.about.p1': 'Narie is a healing lifestyle. We believe in the power of minimalism and natural elements to restore balance. Our candles are crafted with 100% soy wax and natural wood wicks, ensuring a clean burn that is safe for your health and home.',
    'app.about.p2': 'Every vessel is designed to be a piece of decor, adding a touch of sophistication to your sanctuary.',
    'app.about.cta': 'Read our full story',
  },
  vi: {
    'nav.shop': 'CỬA HÀNG',
    'nav.collections': 'BỘ SƯU TẬP',
    'nav.ai': 'CHUYÊN GIA AI',
    'nav.story': 'CÂU CHUYỆN',
    'nav.login': 'ĐĂNG NHẬP',
    'nav.shopAll': 'XEM TẤT CẢ',
    'hero.tagline': 'CHẠM TỐI GIẢN, HƯƠNG TỰ NHIÊN',
    'hero.title': 'Nâng tầm không gian sống bằng những mùi hương tinh tế và nguyên bản.',
    'hero.subtitle': '100% Sáp đậu nành. Bấc gỗ tự nhiên. An toàn sức khỏe.',
    'hero.cta_shop': 'Khám Phá Bộ Sưu Tập',
    'hero.cta_ai': 'Tìm Mùi Hương',
    'products.title': 'Bộ Sưu Tập Bốn Mùa',
    'products.subtitle': 'The Quiet Seasons - Những nốt hương chữa lành.',
    'products.viewAll': 'Xem tất cả',
    'product.tab.description': 'Cảm Hứng',
    'product.tab.details': 'Chi Tiết',
    'product.tab.shipping': 'Vận Chuyển',
    'product.burnTime': 'Thời Gian Đốt',
    'product.burnTimeValue': '50-60 giờ',
    'product.weight': 'Trọng Lượng',
    'product.weightValue': '8.5 oz (240g)',
    'product.ingredients': 'Thành Phần',
    'product.ingredientsValue': 'Sáp Đậu Nành Tự Nhiên, Bấc Gỗ FSC, Tinh Dầu Cao Cấp',
    'product.shippingValue': 'Miễn phí vận chuyển cho đơn hàng trên 1.000.000đ. Giao hàng trong 2-3 ngày.',
    'product.addToCart': 'Thêm Vào Giỏ',
    'product.category.signature': 'The Quiet Seasons',
    'product.category.seasonal': 'Bộ Sưu Tập Mùa',
    'product.category.limited': 'Phiên Bản Giới Hạn',
    'ai.tagline': 'Chuyên Gia Mùi Hương AI',
    'ai.title': 'Mô tả khoảnh khắc, tìm mùi hương chữa lành.',
    'ai.subtitle': 'Dù là "buổi sáng yên tĩnh bên tách trà" hay "góc bếp ấm cúng", AI sẽ tìm ra mùi hương dành riêng cho bạn.',
    'ai.placeholder': 'vd: Cảm giác nắng thu xuyên qua kẽ lá...',
    'ai.button.loading': 'Đang tìm kiếm...',
    'ai.button.idle': 'Tìm Kiếm',
    'ai.error': 'Đã xảy ra lỗi. Vui lòng thử lại.',
    'ai.result.concept': 'Gợi Ý Của Bạn',
    'ai.result.notes': 'Nốt Hương',
    'ai.result.why': 'Sự phù hợp:',
    'ai.result.again': 'Thử lại',
    'ai.empty.text': 'Mùi hương của bạn đang chờ...',
    'blog.title': 'Góc Chữa Lành',
    'blog.subtitle': 'Những câu chuyện nhỏ về lối sống và sự bình yên.',
    'blog.p1.title': 'Góc Ban Công',
    'blog.p1.desc': 'Biến khoảng không gian nhỏ thành nơi trú ẩn cho cà phê sáng và sự suy ngẫm.',
    'blog.p2.title': 'Chuyện Tối Tối',
    'blog.p2.desc': 'Nghi thức thư giãn sau ngày dài: ánh sáng dịu, nhạc nhẹ và mùi hương hoàn hảo.',
    'blog.p3.title': 'Nhà Có Hàng Xóm',
    'blog.p3.desc': 'Niềm vui của sự chia sẻ hơi ấm và cộng đồng trong cuộc sống thường ngày.',
    'director.title': 'Lời Ngỏ Từ Giám Đốc Sáng Tạo',
    'director.text': 'Narie không chỉ là nến, đó là khoảng lặng giữa những khoảnh khắc. Là hơi thở sâu khi bạn bước qua cánh cửa nhà. Chúng tôi tạo ra "The Quiet Seasons" để tôn vinh nhịp điệu của tự nhiên và nhịp điệu của trái tim bạn.',
    'director.signoff': '- Giám Đốc Sáng Tạo Narie',
    'footer.desc': 'Narie Candle - Chạm Tối Giản, Hương Tự Nhiên.',
    'footer.shop': 'Cửa Hàng',
    'footer.company': 'Về Narie',
    'footer.newsletter': 'Nhận Thư',
    'footer.newsletter_desc': 'Nhận thư từ Narie về những mùi hương mới.',
    'footer.subscribe': 'Đăng Ký',
    'footer.rights': 'Đã đăng ký bản quyền.',
    'footer.links.all': 'Tất Cả Nến',
    'footer.links.sig': 'Dòng Đặc Trưng',
    'footer.links.seasonal': 'Bộ Sưu Tập Mùa',
    'footer.links.access': 'Phụ Kiện',
    'footer.links.story': 'Câu Chuyện',
    'footer.links.sus': 'Bền Vững',
    'footer.links.stock': 'Cửa Hàng',
    'footer.links.contact': 'Liên Hệ',
    'footer.links.privacy': 'Chính Sách',
    'footer.links.terms': 'Điều Khoản',
    'app.quote': '"Chúng tôi tin rằng mùi hương không chỉ là hương thơm; đó là ký ức đang chờ được thắp sáng."',
    'app.about.title': 'Về Narie',
    'app.about.p1': 'Narie là một lối sống chữa lành. Chúng tôi tin vào sức mạnh của sự tối giản và các yếu tố tự nhiên để khôi phục sự cân bằng. Nến của chúng tôi được làm từ 100% sáp đậu nành và bấc gỗ tự nhiên, đảm bảo cháy sạch, an toàn cho sức khỏe và ngôi nhà của bạn.',
    'app.about.p2': 'Mỗi hũ nến được thiết kế như một món đồ trang trí, thêm nét tinh tế cho không gian riêng của bạn.',
    'app.about.cta': 'Đọc câu chuyện đầy đủ',
  }
};

export const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};